global:
  sendAnonymousUsage: false
  checkNewVersion: false
  
entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"

api:
  dashboard: true
  debug: true


# Configuring Multiple Filters (DEMO mode: restrict or adjust as needed)
accessLog:
  filePath: "logs/access.log"
  format: json
  filters:
    statusCodes:
      - "200"
      - "300-302"
      - "400-500"
    retryAttempts: true
    minDuration: "10ms"

metrics:
  prometheus:
    entryPoint: web
    buckets:
      - 0.1
      - 0.5
      - 1
      - 5
      - 10
      - 20
      - 50
      - 100

tracing:
  serviceName: traefik

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: miniapp_public
  # added for mkcert usage
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# to be used later for let's encrypt with a public domain only (in STAGING or PROD modes)
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: %%TRAEFIK_EMAIL%%
#       storage: /etc/traefik/acme/acme.json
#       httpChallenge:
#         entryPoint: web